import { ManagerFinanceAccess } from "../../../components/manager-finance-access";
import { getTeamSummary } from "../../../lib/team-summary";
import { Badge } from "@andthenn/ui";
import { CalendarDays, CircleAlert, Gauge, Timer } from "lucide-react";
import Link from "next/link";
import { PageHeading } from "../../../components/page-heading";
import { resolveActorContext } from "../../../lib/actor-context";

const day = 86_400_000;

export default async function TeamPage() {
  const actor = await resolveActorContext(); if (!actor) return null;
  const { rows, timezone, windowStart, windowEnd } = await getTeamSummary(actor);
  const planned = rows.reduce((sum, row) => sum + row.planned, 0); const available = rows.reduce((sum, row) => sum + row.available, 0);
  return <><PageHeading eyebrow={`${rows.length} active people`} title="Team load" description={`${timezone} availability and assigned work due through ${windowStart.toLocaleDateString()}–${new Date(windowEnd.getTime() - day).toLocaleDateString()}. Overdue backlog is included; future work, completed tasks, and removed assignments are excluded.`}/>
    <section aria-label="Team load summary" className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={Gauge} label="Studio utilization" value={available ? `${Math.round(planned / available * 100)}%` : "—"}/><Summary icon={Timer} label="Planned / available" value={`${Math.round(planned / 60)}h / ${Math.round(available / 60)}h`}/><Summary icon={CircleAlert} label="Capacity risks" value={String(rows.filter((row) => row.risk === "OVERLOADED" || row.risk === "BUSY").length)}/><Summary icon={CalendarDays} label="Overdue assignments" value={String(rows.reduce((sum, row) => sum + row.overdue, 0))}/></section>
    <section className="surface overflow-hidden rounded-2xl"><div className="hidden grid-cols-[minmax(200px,1.4fr)_110px_130px_100px_120px] border-b border-zinc-100 px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-zinc-500 md:grid"><span>Person</span><span>Active work</span><span>Load</span><span>Overdue</span><span>Risk</span></div><div className="divide-y divide-zinc-100">{rows.map((person) => <article id={`member-${person.id}`} key={person.id} className="grid gap-4 p-5 md:grid-cols-[minmax(200px,1.4fr)_110px_130px_100px_120px] md:items-center"><div className="min-w-0"><strong className="block truncate text-sm">{person.name}</strong><span className="mt-1 block truncate text-xs text-zinc-500">{person.role} · {person.accountType === "TEMPORARY" ? `until ${person.expiresAt?.toLocaleDateString() ?? "expiry"}` : person.email}</span>{actor.role === "FOUNDER" && person.role === "MANAGER" && <ManagerFinanceAccess membershipId={person.id} granted={person.financeAccess}/>}<div className="mt-2">{person.work.map((task) => <Link key={task.id} href={`/tasks/${task.id}`} className="block py-2 text-xs text-violet-700">{task.name}</Link>)}</div></div><span className="text-sm font-semibold">{person.activeCount} task{person.activeCount === 1 ? "" : "s"}{person.missing ? <small className="block font-normal text-amber-700">{person.missing} unestimated</small> : null}</span><div><div className="flex justify-between text-xs font-semibold"><span>{Math.round(person.planned / 60)}h</span><span className="text-zinc-500">{person.utilization === null ? "No capacity" : `${person.utilization}%`}</span></div><div className="mt-2 h-1.5 rounded-full bg-zinc-100"><div className={`h-full rounded-full ${person.risk === "OVERLOADED" ? "bg-rose-500" : person.risk === "BUSY" ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${Math.min(100, person.utilization ?? 0)}%` }}/></div></div><span className={person.overdue ? "text-sm font-bold text-rose-700" : "text-sm text-zinc-500"}>{person.overdue}</span><Badge tone={person.risk === "OVERLOADED" ? "rose" : person.risk === "BUSY" ? "amber" : person.risk === "AVAILABLE" ? "green" : "neutral"}>{person.risk}</Badge></article>)}</div>{!rows.length && <p className="p-10 text-center text-sm text-zinc-500">No active internal teammates.</p>}</section>
    <p className="mt-3 text-xs text-zinc-500">Individual assignment commitments include primary and collaborator estimates; they are not unique project effort. <Link href="/workload" className="font-bold text-violet-700">Open planning detail</Link></p></>;
}

function Summary({ icon: Icon, label, value }: { icon: typeof Gauge; label: string; value: string }) { return <div className="surface rounded-2xl p-4"><Icon size={17} className="text-violet-600"/><p className="mt-3 text-xs font-semibold text-zinc-500">{label}</p><p className="display mt-1 text-2xl font-bold">{value}</p></div>; }
