import { ProjectFinance } from "../../../../components/project-finance";
import { ProjectDiscussion } from "../../../../components/project-discussion";
import { projectHealth } from "../../../../lib/calendar";
import { isCurrentFinalFile } from "../../../../lib/final-file";
import { memberships, profiles, clientMemberships, archiveJobs, projectClosureChecklistItems, activityEvents, and, clients, createDatabase, deliverables, eq, fileAssets, fileVersions, inArray, projects, reviewHubs, reviewShares, tasks, workflowStages } from "@andthenn/db";
import { isOperationalLeader } from "@andthenn/domain";
import { ProjectClientAccess } from "../../../../components/project-client-access";
import { ProjectCloseout } from "../../../../components/project-closeout";
import { Badge } from "@andthenn/ui";
import { Activity, Files, FolderKanban, ListChecks, ScanEye } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeading } from "../../../../components/page-heading";
import { resolveActorContext } from "../../../../lib/actor-context";
import { ClientProjectReviews } from "../../../../components/client-project-reviews";
import { canReadProject, canReadTask, isResourceId } from "../../../../lib/resource-access";

export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await resolveActorContext(); if (!actor) return null; const { id } = await params; const { db } = createDatabase();
  if (!isResourceId(id)) notFound();
  const [project] = await db.select({ id: projects.id, name: projects.name, status: projects.status, deadline: projects.deadline, notes: projects.notes, clientId: clients.id, client: clients.name }).from(projects).innerJoin(clients, eq(clients.id, projects.clientId)).where(and(eq(projects.id, id), eq(projects.organizationId, actor.organizationId))).limit(1); if (!project) notFound();
  const [allTasks, outputRows] = await Promise.all([
    db.select({ id: tasks.id, name: tasks.name, status: tasks.executionStatus, priority: tasks.priority, dueAt: tasks.dueAt, output: deliverables.name, stage: workflowStages.name }).from(tasks).innerJoin(deliverables, eq(deliverables.id, tasks.deliverableId)).leftJoin(workflowStages, eq(workflowStages.id, tasks.currentWorkflowStageId)).where(and(eq(deliverables.projectId, id), eq(tasks.organizationId, actor.organizationId))),
    db.select({ id: deliverables.id, name: deliverables.name, status: deliverables.status, dueAt: deliverables.dueAt, format: deliverables.format }).from(deliverables).where(and(eq(deliverables.projectId, id), eq(deliverables.organizationId, actor.organizationId))),
  ]);
  if (!canReadProject(actor, { id: project.id, clientId: project.clientId, taskIds: allTasks.map((task) => task.id) })) notFound();
  const rows = actor.role === "CLIENT" ? [] : allTasks.filter((task) => canReadTask(actor, { id: project.id, clientId: project.clientId, taskId: task.id, taskIds: [task.id] }));
  const taskIds = (actor.role === "CLIENT" ? allTasks : rows).map((task) => task.id);
  const [fileRows, reviewRows, activityRows] = await Promise.all([
    taskIds.length ? db.select({ id: fileVersions.id, taskId: tasks.id, task: tasks.name, name: fileAssets.logicalName, filename: fileVersions.filename, version: fileVersions.versionNumber, status: fileVersions.processingStatus, lockedAt: fileVersions.lockedAt, isCurrentFinal: isCurrentFinalFile, createdAt: fileVersions.createdAt }).from(fileVersions).innerJoin(fileAssets, eq(fileAssets.id, fileVersions.fileAssetId)).innerJoin(tasks, eq(tasks.id, fileAssets.taskId)).where(and(eq(fileVersions.organizationId, actor.organizationId), inArray(tasks.id, taskIds))) : Promise.resolve([]),
    taskIds.length ? db.select({ id: reviewShares.id, taskId: reviewHubs.taskId, status: reviewShares.status, recipient: reviewShares.recipientSnapshot, expiresAt: reviewShares.expiresAt, sharedAt: reviewShares.sharedAt }).from(reviewShares).innerJoin(reviewHubs, eq(reviewHubs.id, reviewShares.reviewHubId)).where(and(eq(reviewShares.organizationId, actor.organizationId), inArray(reviewHubs.taskId, taskIds))) : Promise.resolve([]),
    db.select({ id: activityEvents.id, eventType: activityEvents.eventType, entityType: activityEvents.entityType, entityId: activityEvents.entityId, createdAt: activityEvents.createdAt }).from(activityEvents).where(eq(activityEvents.organizationId, actor.organizationId)).orderBy(activityEvents.createdAt),
  ]);
  const files = fileRows.filter((file) => actor.role !== "CLIENT" || file.isCurrentFinal); const activity = activityRows.filter((event) => ((event.entityType === "PROJECT" && event.entityId === id) || (event.entityType === "TASK" && taskIds.includes(event.entityId))) && (actor.role !== "CLIENT" || event.eventType === "project.activated" || event.eventType.startsWith("review.") || event.eventType.startsWith("file."))).slice(-20).reverse();
  const [checklist, archives] = isOperationalLeader(actor.role) ? await Promise.all([
    db.select({ id: projectClosureChecklistItems.id, label: projectClosureChecklistItems.label, completedAt: projectClosureChecklistItems.completedAt }).from(projectClosureChecklistItems).where(and(eq(projectClosureChecklistItems.organizationId, actor.organizationId), eq(projectClosureChecklistItems.projectId, id))),
    db.select({ status: archiveJobs.status }).from(archiveJobs).where(and(eq(archiveJobs.organizationId, actor.organizationId), eq(archiveJobs.projectId, id))).orderBy(archiveJobs.createdAt),
  ]) : [[], []];
  const linkedClients = isOperationalLeader(actor.role) ? await db.select({ id: memberships.id, name: profiles.displayName }).from(clientMemberships).innerJoin(memberships, eq(memberships.id, clientMemberships.membershipId)).innerJoin(profiles, eq(profiles.id, memberships.profileId)).where(and(eq(clientMemberships.organizationId, actor.organizationId), eq(clientMemberships.clientId, project.clientId), eq(memberships.role, "CLIENT"))) : [];
  const done = allTasks.filter((task) => task.status === "COMPLETED").length; const health = projectHealth(allTasks);
  return <><PageHeading eyebrow={`${project.client} · ${project.status.replaceAll("_", " ")}`} title={project.name} description={`Due ${project.deadline.toLocaleDateString()} · ${done} of ${allTasks.length} tasks complete`} action={actor.role !== "CLIENT" ? <div className="flex flex-wrap gap-2"><Link href={`/work?new=task&project=${project.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-violet-600 px-3 text-sm font-bold text-white">New task</Link><Link href={`/clients/${project.clientId}`} className="inline-flex min-h-11 items-center rounded-xl border border-zinc-200 bg-white px-3 text-sm font-bold">Client record</Link></div> : undefined}/>
    <nav className="mb-4 flex gap-2 overflow-x-auto pb-1 text-sm" aria-label="Project sections">{[["overview", "Overview"], ...(actor.role === "CLIENT" ? [] : [["tasks", "Tasks"], ["discussion", "Discussion"]]), ["outputs", "Outputs"], ["review", "Review"], ["files", "Files"], ["activity", "Activity"]].map(([anchor, label], index) => <a key={anchor} href={`#${anchor}`} className={`inline-flex min-h-11 shrink-0 items-center rounded-xl px-3 font-bold ${index === 0 ? "bg-zinc-950 text-white" : "border border-zinc-200 bg-white"}`}>{label}</a>)}</nav>
    <section id="overview" className="mb-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Overview icon={FolderKanban} label={project.status === "COMPLETED" ? "Lifecycle" : "Health"} value={project.status === "COMPLETED" ? "Completed" : health}/><Overview icon={ListChecks} label="Task progress" value={`${done} / ${allTasks.length}`}/><Overview icon={ScanEye} label="Active reviews" value={String(reviewRows.filter((review) => review.status === "ACTIVE").length)}/><Overview icon={Files} label={actor.role === "CLIENT" ? "Final files" : "File versions"} value={String(files.length)}/></section>
    {isOperationalLeader(actor.role) && <ProjectCloseout projectId={id} status={project.status} outputs={outputRows} checklist={checklist.map((item) => ({ ...item, completed: Boolean(item.completedAt) }))} archiveStatus={archives.at(-1)?.status ?? null}/>}
    {isOperationalLeader(actor.role) && <ProjectClientAccess projectId={id} clients={linkedClients}/>}
    {project.notes && <p className="surface mb-4 rounded-2xl p-5 text-sm leading-6 text-zinc-600">{project.notes}</p>}
    {actor.role === "CLIENT" && <ClientProjectReviews projectId={id}/>}
    {actor.role !== "CLIENT" && <section id="tasks" className="surface mb-4 overflow-hidden rounded-2xl"><SectionTitle icon={ListChecks} title="Tasks" detail="Execution status and workflow phase remain separate."/><div className="divide-y divide-zinc-100">{rows.map((task) => <Link href={`/tasks/${task.id}`} key={task.id} className="grid gap-2 p-4 transition hover:bg-violet-50/40 sm:grid-cols-[1fr_150px_130px] sm:items-center"><span><strong className="block text-sm">{task.name}</strong><small className="text-zinc-500">{task.output} · {task.stage ?? "—"} · {task.priority}</small></span><Badge tone={task.status === "COMPLETED" ? "green" : task.status === "BLOCKED" ? "rose" : task.status === "WAITING" ? "amber" : "violet"}>{task.status.replaceAll("_", " ")}</Badge><span className="text-xs text-zinc-500">Due {task.dueAt.toLocaleDateString()}</span></Link>)}</div>{!rows.length && <p className="p-8 text-sm text-zinc-500">No authorized tasks in this project.</p>}</section>}
    <section id="outputs" className="surface mb-4 overflow-hidden rounded-2xl"><SectionTitle icon={FolderKanban} title="Outputs" detail="The promised project deliverables and their current readiness."/><div className="divide-y divide-zinc-100">{outputRows.map((output) => <div key={output.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_180px_140px] sm:items-center"><span><strong className="block text-sm">{output.name}</strong><small className="text-zinc-500">{output.format || "Format to be confirmed"}</small></span><Badge tone={output.status === "COMPLETED" ? "green" : output.status === "READY_FOR_MANAGER_CONFIRMATION" ? "cyan" : "neutral"}>{output.status.replaceAll("_", " ")}</Badge><span className="text-xs text-zinc-500">{output.dueAt ? `Due ${output.dueAt.toLocaleDateString()}` : "No separate due date"}</span></div>)}</div>{!outputRows.length && <p className="p-8 text-sm text-zinc-500">No outputs recorded yet.</p>}</section>
    <section id="review" className="surface mb-4 overflow-hidden rounded-2xl"><SectionTitle icon={ScanEye} title="Review" detail={actor.role === "CLIENT" ? "Shares addressed through this project; secure guest links remain a separate boundary." : "Version-pinned client review shares across project tasks."}/><div className="divide-y divide-zinc-100">{reviewRows.map((review) => <div key={review.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_130px_150px] sm:items-center"><span className="text-sm font-bold">{review.recipient ?? "Copy-link reviewer"}</span><Badge tone={review.status === "ACTIVE" ? "green" : "neutral"}>{review.status}</Badge><span className="text-xs text-zinc-500">{review.expiresAt ? `Expires ${review.expiresAt.toLocaleDateString()}` : "No expiry"}</span></div>)}</div>{!reviewRows.length && <p className="p-8 text-sm text-zinc-500">No review shares yet.</p>}</section>
    <section id="files" className="surface mb-4 overflow-hidden rounded-2xl"><SectionTitle icon={Files} title={actor.role === "CLIENT" ? "Final deliveries" : "Files"} detail={actor.role === "CLIENT" ? "Only Client-approved, explicitly published versions are shown." : "Open the task to upload, clear for review, record Client approval, publish or share a version."}/><div className="divide-y divide-zinc-100">{files.map((file) => actor.role === "CLIENT" ? <a href={`/api/files/${file.id}`} key={file.id} className="grid gap-2 p-4 sm:grid-cols-[1fr_140px] sm:items-center"><span><strong className="block text-sm">{file.name} · v{file.version}</strong><small className="text-zinc-500">{file.filename}</small></span><Badge tone="green">APPROVED FINAL</Badge></a> : <Link key={file.id} href={`/tasks/${file.taskId}`} className="grid gap-2 p-4 transition hover:bg-violet-50/40 sm:grid-cols-[1fr_140px] sm:items-center"><span><strong className="block text-sm">{file.name} · v{file.version}</strong><small className="text-zinc-500">{file.task} · {file.filename}</small></span><Badge tone={file.isCurrentFinal ? "green" : file.status === "READY" ? "cyan" : "amber"}>{file.isCurrentFinal ? "APPROVED" : file.status}</Badge></Link>)}</div>{!files.length && <p className="p-8 text-sm text-zinc-500">No visible file versions yet.</p>}</section>
    <ProjectFinance projectId={id} actor={actor}/><ProjectDiscussion projectId={id} actor={actor}/>
    <section id="activity" className="surface overflow-hidden rounded-2xl"><SectionTitle icon={Activity} title="Activity" detail="Auditable project and task events, newest first."/><div className="divide-y divide-zinc-100">{activity.map((event) => <div key={event.id} className="flex items-center justify-between gap-4 p-4"><span className="text-sm font-semibold">{event.eventType.replaceAll(".", " ").replaceAll("_", " ")}</span><time className="shrink-0 text-xs text-zinc-500">{event.createdAt.toLocaleString()}</time></div>)}</div>{!activity.length && <p className="p-8 text-sm text-zinc-500">No project activity recorded yet.</p>}</section></>;
}

function Overview({ icon: Icon, label, value }: { icon: typeof FolderKanban; label: string; value: string }) { return <div className="surface rounded-2xl p-4"><Icon size={17} className="text-violet-600"/><p className="mt-3 text-xs font-semibold text-zinc-500">{label}</p><p className="display mt-1 text-xl font-bold">{value}</p></div>; }
function SectionTitle({ icon: Icon, title, detail }: { icon: typeof FolderKanban; title: string; detail: string }) { return <div className="flex items-start gap-3 border-b border-zinc-100 p-5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon size={17}/></span><div><h2 className="display text-lg font-bold">{title}</h2><p className="mt-1 text-xs text-zinc-500">{detail}</p></div></div>; }
