import { Badge, Button } from "@andthenn/ui";
import { Activity, CalendarDays, ChevronRight, CircleDollarSign, Files, LayoutDashboard, MoreHorizontal, UsersRound } from "lucide-react";
import Link from "next/link";
import { ProjectBoard } from "../../../../components/project-board";
export default async function ProjectPage({ params }: { params: Promise<{ id: string }> }) {
  await params;
  return <><nav aria-label="Breadcrumb" className="mb-4 flex items-center gap-1.5 text-xs text-zinc-400"><Link href="/projects">Projects</Link><ChevronRight size={12} /><span>Aster House</span><ChevronRight size={12} /><span className="text-zinc-700">Monsoon Stories</span></nav>
    <div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end"><div className="flex min-w-0 items-center gap-4"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-zinc-950 text-sm font-black text-white">AH</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge tone="green">Active</Badge><span className="text-xs font-bold text-zinc-400">AT-042</span></div><h1 className="display mt-1 truncate text-3xl font-bold">Monsoon Stories</h1><p className="mt-1 text-xs text-zinc-400">Aster House · Owner Maya Shah · Due 12 August 2026</p></div></div><div className="ml-auto flex gap-2"><Button variant="secondary"><UsersRound size={15} /> Team</Button><Button variant="secondary" aria-label="More project actions"><MoreHorizontal size={16} /></Button></div></div>
    <div className="mb-5 flex gap-1 overflow-x-auto border-b border-zinc-200">{[[LayoutDashboard,"Overview"],[Activity,"Workflow"],[Files,"Files"],[CircleDollarSign,"Commercial"],[CalendarDays,"Timeline"]].map(([Icon,label], index) => {const C=Icon as typeof Activity; return <button key={String(label)} className={`flex min-h-11 shrink-0 items-center gap-2 border-b-2 px-3 text-xs font-bold ${index === 1 ? "border-violet-600 text-violet-700" : "border-transparent text-zinc-400 hover:text-zinc-800"}`}><C size={14} />{String(label)}</button>})}</div>
    <div className="mb-4 grid gap-3 md:grid-cols-3"><div className="surface rounded-2xl p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">Deliverable progress</p><div className="mt-3 flex items-end justify-between"><p className="display text-2xl font-bold">4 <span className="text-sm text-zinc-400">of 6</span></p><span className="text-xs font-bold text-emerald-600">68%</span></div><div className="mt-3 h-1.5 rounded-full bg-zinc-100"><div className="h-full w-[68%] rounded-full bg-violet-500" /></div></div><div className="surface rounded-2xl p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">Time tracked</p><p className="display mt-3 text-2xl font-bold">84.5h <span className="text-sm text-zinc-400">/ 120h</span></p><p className="mt-3 text-xs text-zinc-400">35.5 hours remaining</p></div><div className="rounded-2xl bg-[#171826] p-4 text-white"><p className="text-[10px] font-bold uppercase tracking-widest text-cyan-300">Next milestone</p><p className="mt-3 text-sm font-bold">Client review · Hero film</p><p className="mt-2 text-xs text-zinc-500">V2 due today at 6:00 PM</p></div></div>
    <ProjectBoard />
  </>;
}
