import { and, calendarSyncRecords, createDatabase, desc, eq, integrationConnections, jobRuns } from "@andthenn/db";
import { notFound } from "next/navigation";
import { PageHeading } from "../../../components/page-heading";
import { connectGoogleCalendar, retryCalendarSync } from "../operations/actions";
import { resolveActorContext } from "../../../lib/actor-context";
export default async function AdminPage() {
  const actor = await resolveActorContext(); if (!actor || actor.role !== "MANAGER") notFound(); const { db } = createDatabase();
  const [connections, syncs, failedJobs] = await Promise.all([db.select().from(integrationConnections).where(eq(integrationConnections.organizationId, actor.organizationId)), db.select().from(calendarSyncRecords).where(and(eq(calendarSyncRecords.organizationId, actor.organizationId), eq(calendarSyncRecords.status, "FAILED"))).orderBy(desc(calendarSyncRecords.updatedAt)).limit(25), db.select().from(jobRuns).where(and(eq(jobRuns.organizationId, actor.organizationId), eq(jobRuns.status, "FAILED"))).orderBy(desc(jobRuns.updatedAt)).limit(25)]);
  const calendar = connections.find((row) => row.provider === "GOOGLE" && row.kind === "CALENDAR");
  return <><PageHeading eyebrow="Manager only" title="Administration" description="Integration health and recoverable operational failures."/>
    <section className="surface max-w-3xl rounded-2xl p-5"><h2 className="display text-lg font-bold">Google Calendar</h2><p className="mt-1 text-sm text-zinc-500">One-way ERP-to-Calendar sync. ERP remains the source of truth.</p>{calendar ? <p className="mt-4 text-sm font-semibold">{calendar.status} · {calendar.externalAccountId}</p> : <form action={connectGoogleCalendar} className="mt-4 flex gap-2"><input required name="externalAccountId" placeholder="Calendar account ID" className="h-10 flex-1 rounded-xl border border-zinc-200 px-3 text-sm"/><button className="rounded-xl bg-violet-600 px-4 text-sm font-bold text-white">Connect</button></form>}</section>
    <section className="surface mt-5 max-w-3xl rounded-2xl p-5"><h2 className="display text-lg font-bold">Calendar recovery queue</h2>{syncs.map((sync) => <div key={sync.id} className="mt-3 flex items-center justify-between rounded-xl bg-zinc-50 p-3 text-sm"><span>{sync.objectType} · {sync.failureDetail ?? "Failed sync"}</span><form action={retryCalendarSync}><input type="hidden" name="syncId" value={sync.id}/><button className="font-bold text-violet-600">Retry</button></form></div>)}{!syncs.length && <p className="mt-3 text-sm text-zinc-500">No failed calendar synchronizations.</p>}</section>
    <section className="surface mt-5 max-w-3xl rounded-2xl p-5"><h2 className="display text-lg font-bold">Failed jobs</h2>{failedJobs.map((job) => <p key={job.id} className="mt-3 rounded-xl bg-zinc-50 p-3 text-sm">{job.type}: {job.lastFailure ?? "Failure awaiting detail"}</p>)}{!failedJobs.length && <p className="mt-3 text-sm text-zinc-500">No failed jobs.</p>}</section></>;
}
