import { and, createDatabase, deliverables, eq, fileVersions, gt, isNull, or, projects, reviewHubs, reviewShares, sql, tasks } from "@andthenn/db";
import { resolveActorContext } from "../lib/actor-context";
import { canReadProject } from "../lib/resource-access";
import { ClientReviewForm } from "./client-review-form";

export async function ClientProjectReviews({ projectId }: { projectId: string }) {
  const actor = await resolveActorContext();
  if (!actor || actor.role !== "CLIENT") return null;
  const { db } = createDatabase();
  const rows = await db.select({ id: reviewShares.id, projectId: projects.id, clientId: projects.clientId, filename: fileVersions.filename, fileVersionId: fileVersions.id, fileVersion: fileVersions.versionNumber, version: tasks.version, taskStatus: tasks.executionStatus, contentType: fileVersions.contentType, decided: sql<boolean>`exists (select 1 from file_approvals a where a.task_id=${tasks.id} and a.file_version_id=${fileVersions.id} and a.approval_kind='CLIENT' and a.reopened_at is null) or not exists (select 1 from file_approvals a where a.task_id=${tasks.id} and a.file_version_id=${fileVersions.id} and a.approval_kind='INTERNAL' and a.reopened_at is null)` }).from(reviewShares).innerJoin(reviewHubs, eq(reviewHubs.id, reviewShares.reviewHubId)).innerJoin(tasks, eq(tasks.id, reviewHubs.taskId)).innerJoin(deliverables, eq(deliverables.id, tasks.deliverableId)).innerJoin(projects, eq(projects.id, deliverables.projectId)).innerJoin(fileVersions, eq(fileVersions.id, reviewShares.fileVersionId)).where(and(eq(projects.id, projectId), eq(reviewShares.organizationId, actor.organizationId), eq(reviewShares.status, "ACTIVE"), or(isNull(reviewShares.expiresAt), gt(reviewShares.expiresAt, new Date())), eq(fileVersions.processingStatus, "READY"), sql`not exists (select 1 from task_review_selections selection where selection.task_id = ${tasks.id} and selection.file_version_id <> ${fileVersions.id})`));
  const visible = rows.filter((row) => canReadProject(actor, { id: row.projectId, clientId: row.clientId }) && row.taskStatus !== "COMPLETED");
  if (!visible.length) return null;
  return <section data-walkthrough="client-review" id="client-decisions" aria-label="Client decisions" className="surface mb-4 rounded-2xl p-5"><h2 className="display text-lg font-bold">Your review decisions</h2><p className="mt-1 text-sm text-zinc-600">Review the exact shared version, then approve or request changes.</p><div className="mt-4 space-y-5">{visible.map((row) => { const media = `/api/files/${row.fileVersionId}?reviewShareId=${row.id}&preview=1`; return <article key={row.id} className="rounded-xl border border-zinc-200 p-4"><h3 className="break-words text-sm font-bold">{row.filename} · v{row.fileVersion}</h3>{row.contentType.startsWith("video/") ? <video controls preload="metadata" src={media} className="mt-3 max-h-96 w-full rounded-xl bg-zinc-950" aria-label={`Review ${row.filename}`}/> : <a href={media} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-violet-700">Open version preview</a>}<ClientReviewForm shareId={row.id} version={row.version} decided={row.decided}/></article>; })}</div></section>;
}
