"use client";
import { PreservingForm } from "./preserving-form";
import { useActionState } from "react";
import { runDeliveryCommand } from "../app/(erp)/delivery-command";
export function DeliveryActions({ taskId, fileVersionId, taskVersion }: { taskId: string; fileVersionId: string; taskVersion: number }) {
  return <div className="w-full space-y-3"><DeliveryForm taskId={taskId} fileVersionId={fileVersionId} taskVersion={taskVersion} command="clear" label="Clear for Client review"/><details className="rounded-xl border border-zinc-200 bg-white p-3"><summary className="min-h-11 cursor-pointer font-semibold">Record Client approval received externally</summary><DeliveryForm taskId={taskId} fileVersionId={fileVersionId} taskVersion={taskVersion} command="external" label="Record Client approval"><label className="block">Client approver<input name="clientApprover" required className="control mt-1"/></label><label className="block">Approval received at<input type="datetime-local" name="approvedAt" required className="control mt-1"/></label><label className="block">Channel<select name="source" className="control mt-1"><option value="EMAIL">Email</option><option value="WHATSAPP">WhatsApp</option><option value="OTHER">Other</option></select></label><label className="block">Evidence reference<input name="evidence" required className="control mt-1" placeholder="Message reference or evidence URL"/></label><label className="block">Approval note<textarea name="note" required minLength={3} className="control mt-1"/></label></DeliveryForm></details><DeliveryForm taskId={taskId} fileVersionId={fileVersionId} taskVersion={taskVersion} command="publish" label="Publish final delivery"/></div>;
}
function DeliveryForm({ taskId, fileVersionId, taskVersion, command, label, children }: { taskId: string; fileVersionId: string; taskVersion: number; command: string; label: string; children?: React.ReactNode }) {
  const [state, action, pending] = useActionState(runDeliveryCommand, {});
  return <PreservingForm action={action} className="space-y-2"><input type="hidden" name="taskId" value={taskId}/><input type="hidden" name="fileVersionId" value={fileVersionId}/><input type="hidden" name="expectedTaskVersion" value={taskVersion}/><input type="hidden" name="command" value={command}/>{children}<button disabled={pending} className="min-h-11 rounded-xl bg-zinc-950 px-4 font-bold text-white disabled:opacity-50">{pending ? "Saving…" : label}</button>{state.error && <p role="alert" className="text-rose-700">{state.error}</p>}{state.success && <p role="status" className="text-emerald-700">{state.success}</p>}</PreservingForm>;
}
