"use client";
import { Badge, Button, cn } from "@andthenn/ui";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { Bot, Check, ChevronDown, FileAudio, FileText, LockKeyhole, Mail, MessageCircle, Paperclip, Plus, Send, UserRoundCheck } from "lucide-react";
import { useState } from "react";
import { intakeItems } from "../lib/demo-data";

export function IntakeWorkbench() {
  const [selected, setSelected] = useState(intakeItems[0]!.id);
  const [claimed, setClaimed] = useState(true);
  const reduced = useReducedMotion();
  const active = intakeItems.find((item) => item.id === selected)!;
  return <div className="-m-4 md:-m-7 xl:-m-9">
    <div className="flex flex-col border-b border-zinc-200 bg-[#f6f5f1] px-4 py-5 md:flex-row md:items-end md:justify-between md:px-7 xl:px-9"><div><div className="mb-2 flex items-center gap-2"><Badge tone="violet">Shared queue</Badge><span className="text-xs text-zinc-400">4 unprocessed</span></div><h1 className="display text-3xl font-bold">Intake control</h1><p className="mt-1 text-sm text-zinc-500">Preserve evidence. Shape the brief. Route it once.</p></div><Button className="mt-4 md:mt-0"><Plus size={16} /> Manual intake</Button></div>
    <div className="grid min-h-[calc(100vh-153px)] bg-white lg:grid-cols-[330px_1fr] xl:grid-cols-[380px_1fr]">
      <aside className="border-r border-zinc-200"><div className="flex items-center justify-between border-b border-zinc-100 p-4"><button className="flex items-center gap-2 text-sm font-bold">All sources <ChevronDown size={14} /></button><button className="text-xs font-semibold text-violet-600">Oldest first</button></div><div className="divide-y divide-zinc-100">
        {intakeItems.map((item) => <button key={item.id} onClick={() => {setSelected(item.id); setClaimed(item.claimed === "You")}} className={cn("relative w-full p-4 text-left transition-colors", selected === item.id ? "bg-violet-50/60" : "hover:bg-zinc-50")}>
          {selected === item.id && <motion.span layoutId="intake-selected" className="absolute inset-y-0 left-0 w-1 bg-violet-500" />}
          <div className="flex items-center gap-2"><span className="grid size-7 place-items-center rounded-lg bg-white text-zinc-500 shadow-sm">{item.source === "Email" ? <Mail size={14} /> : item.source === "WhatsApp" ? <MessageCircle size={14} /> : <FileText size={14} />}</span><span className="text-[11px] font-bold text-zinc-500">{item.source}</span><span className="ml-auto text-[10px] text-zinc-400">{item.received}</span></div><p className="mt-3 truncate text-sm font-bold">{item.subject}</p><p className="mt-1 truncate text-xs text-zinc-500">{item.sender}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-zinc-400">{item.preview}</p><div className="mt-3 flex items-center gap-2">{item.priority === "High" && <Badge tone="rose">High</Badge>}{item.claimed && <span className="text-[10px] font-semibold text-zinc-400">Claimed by {item.claimed}</span>}<span className="ml-auto text-[10px] font-bold text-emerald-600">{item.confidence}% parsed</span></div>
        </button>)}
      </div></aside>
      <AnimatePresence mode="wait"><motion.main key={active.id} initial={reduced ? false : { opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="min-w-0">
        <div className="flex flex-wrap items-center gap-3 border-b border-zinc-100 px-5 py-4"><div className="mr-auto"><p className="text-[10px] font-bold uppercase tracking-wider text-zinc-400">{active.id} · Received 04 Aug, 10:42</p><h2 className="mt-1 text-lg font-bold">{active.subject}</h2></div>{claimed ? <Button variant="secondary" onClick={() => setClaimed(false)}><UserRoundCheck size={15} /> Claimed by you</Button> : <Button onClick={() => setClaimed(true)}><LockKeyhole size={15} /> Claim item</Button>}</div>
        <div className="grid xl:grid-cols-2">
          <section className="border-b border-zinc-200 p-5 xl:border-b-0 xl:border-r"><p className="mb-4 text-[10px] font-bold uppercase tracking-[.16em] text-zinc-400">Original evidence</p><div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-5"><div className="flex items-center gap-3 border-b border-zinc-200 pb-4"><span className="grid size-10 place-items-center rounded-full bg-emerald-500 text-xs font-bold text-white">RH</span><div><p className="text-sm font-bold">Rhea Kapoor</p><p className="text-xs text-zinc-400">+91 98••• 2468 · WhatsApp</p></div></div><div className="space-y-3 py-5 text-sm leading-6 text-zinc-700"><p>Hey team — sharing the updated brief for the monsoon launch. We need the hero cut adapted for social along with the story set.</p><p>Could we have the first round by the 9th? Attaching the PDF and a voice note with context from today’s call.</p></div><div className="grid gap-2 sm:grid-cols-2"><button className="flex items-center gap-3 rounded-xl border border-zinc-200 bg-white p-3 text-left hover:border-violet-300"><FileText size={18} className="text-violet-500" /><span><span className="block text-xs font-bold">Monsoon_Brief.pdf</span><span className="text-[10px] text-zinc-400">2.8 MB</span></span></button><button className="flex items-center gap-3 rounded-xl border border-zinc-200 bg-white p-3 text-left hover:border-cyan-300"><FileAudio size={18} className="text-cyan-500" /><span><span className="block text-xs font-bold">Voice note · 01:24</span><span className="text-[10px] text-zinc-400">Transcribed</span></span></button></div></div>
          </section>
          <section className="bg-[#fbfaf8] p-5"><div className="mb-4 flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-zinc-400">Structured brief</p><span className="flex items-center gap-1.5 text-[10px] font-bold text-violet-600"><Bot size={13} /> AI-assisted · editable</span></div><div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-5">
            <label className="block text-xs font-bold text-zinc-500">Client<select defaultValue="aster" className="mt-2 h-11 w-full rounded-xl border border-zinc-200 bg-white px-3 text-sm text-zinc-900 outline-none focus:border-violet-400"><option value="aster">Aster House</option><option value="new">Create new client…</option></select></label>
            <label className="block text-xs font-bold text-zinc-500">Request summary<textarea defaultValue="Adapt the Monsoon Stories hero film for social and create a six-frame story set. First review requested by 9 August." rows={4} className="mt-2 w-full resize-none rounded-xl border border-zinc-200 p-3 text-sm font-normal leading-6 text-zinc-900 outline-none focus:border-violet-400" /></label>
            <div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold text-zinc-500">Requested due date<input type="date" defaultValue="2026-08-09" className="mt-2 h-11 w-full rounded-xl border border-zinc-200 px-3 font-normal text-zinc-900 outline-none focus:border-violet-400" /></label><label className="block text-xs font-bold text-zinc-500">Intake type<select className="mt-2 h-11 w-full rounded-xl border border-zinc-200 px-3 font-normal text-zinc-900 outline-none focus:border-violet-400"><option>Existing project request</option><option>New project</option><option>New business enquiry</option></select></label></div>
            <div><p className="text-xs font-bold text-zinc-500">Suggested deliverables</p><div className="mt-2 space-y-2">{["Social cutdowns · 3 formats","Instagram story set · 6 frames"].map((item) => <div key={item} className="flex items-center gap-2 rounded-xl bg-zinc-50 p-3 text-sm"><Check size={14} className="text-emerald-500" /><span className="flex-1">{item}</span><span className="text-[10px] font-bold text-emerald-600">High confidence</span></div>)}</div></div>
            <div className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800"><strong>Missing:</strong> final platform aspect ratios and copy approval owner. Confirm during activation.</div>
          </div><div className="mt-4 flex flex-wrap gap-2"><Button disabled={!claimed}><Send size={15} /> Convert to project task</Button><Button variant="secondary" disabled={!claimed}><Paperclip size={15} /> New proposal</Button><Button variant="ghost">Save draft</Button></div></section>
        </div>
      </motion.main></AnimatePresence>
    </div>
  </div>;
}
