import { calendarDate } from "../lib/calendar";
import Link from "next/link";
import type { ActorContext } from "../lib/actor-context";
import { getWorkSummary } from "../lib/work-summary";
import { getTeamSummary } from "../lib/team-summary";
import { getFinanceSummary } from "../lib/finance-summary";
import { WorkSummaryList } from "./work-summary-list";
export async function InternalHomeSupport({ actor }: { actor: ActorContext }) {
  const [{ rows, timezone }, team] = await Promise.all([getWorkSummary(actor), getTeamSummary(actor)]);
  const own = rows.filter((row) => row.mine && row.status !== "COMPLETED"), approvals = rows.filter((row) => row.status !== "COMPLETED" && row.pending && row.reviewerId === actor.membershipId);
  const finance = actor.role === "FOUNDER" ? await getFinanceSummary(actor) : null;
  const today = calendarDate(new Date(), timezone);
  const dailyGroups = [
    { title: "Tasks Due Today", rows: rows.filter((row) => row.status !== "COMPLETED" && calendarDate(row.dueAt, timezone) === today) },
    { title: "Client Feedback", rows: rows.filter((row) => row.status !== "COMPLETED" && row.stateKind === "CLIENT_FEEDBACK_RECEIVED") },
    { title: "Pending Approvals", rows: rows.filter((row) => row.status !== "COMPLETED" && (row.pending || /review|approval/i.test(row.stage ?? ""))) },
  ];
  return <div className="mt-4 space-y-4">{actor.role === "MANAGER" && dailyGroups.map((group) => <section aria-label={group.title} key={group.title} className="surface rounded-2xl"><h2 className="display p-5 text-lg font-bold">{group.title} <span className="text-zinc-500">({group.rows.length})</span></h2><WorkSummaryList rows={group.rows} timezone={timezone}/></section>)}<section className="surface rounded-2xl"><h2 className="display p-5 text-lg font-bold">My Work</h2><p className="px-5 text-sm text-zinc-600">{own.length} open tasks · {approvals.length} approvals assigned to me · My deadlines below</p><WorkSummaryList rows={[...new Map([...approvals, ...own].map((row) => [row.id, row])).values()].slice(0,5)} timezone={timezone}/><Link href="/work?view=personal" className="inline-flex min-h-11 items-center px-5 text-sm font-bold text-violet-700">View all my work</Link></section><section className="surface rounded-2xl p-5"><h2 className="display text-lg font-bold">Team availability and load</h2><p className="mt-2 text-sm text-zinc-600">{team.rows.length} People · {team.rows.filter((person) => person.risk === "AVAILABLE").length} Available · {team.rows.filter((person) => person.risk === "BUSY").length} Busy · {team.rows.filter((person) => person.risk === "OVERLOADED").length} Overloaded</p><div className="mt-3 divide-y divide-zinc-100">{team.rows.slice(0,5).map((person) => <Link key={person.id} href={`/team#member-${person.id}`} className="flex min-h-14 flex-wrap items-center justify-between gap-2 py-3 text-sm"><strong>{person.name}</strong><span>{person.risk.replaceAll("_", " ")} · {person.activeCount} tasks · {person.overdue} overdue</span></Link>)}</div><Link href="/team" className="inline-flex min-h-11 items-center text-sm font-bold text-violet-700">View all Team load</Link></section>{finance && <section className="surface rounded-2xl p-5"><h2 className="display text-lg font-bold">Accounts summary</h2><p className="mt-1 text-sm text-zinc-600">Paid-invoice revenue and recorded expenses, by currency.</p>{finance.totals.map((total) => { const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: total.currency }).format(value/100); return <p key={total.currency} className="mt-3 text-sm">{total.currency} · Revenue {money(total.revenue)} · Expenses {money(total.expense)} · Invoices {money(total.invoiced)} · Operational gross profit {money(total.revenue-total.expense)}</p>; })}<Link href="/accounts" className="inline-flex min-h-11 items-center text-sm font-bold text-violet-700">Open Accounts and estimates</Link></section>}</div>;
}
