"use client";
import { Button, cn } from "@andthenn/ui";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { Check, ChevronDown, Download, Expand, Link2, MessageSquare, MoreHorizontal, Pause, Play, Send, Volume2, X } from "lucide-react";
import { useState } from "react";

const comments = [
  { id: 1, initials: "RK", name: "Rhea Kapoor", time: "00:14", body: "Can we hold this establishing shot for another beat? The transition feels slightly rushed.", age: "18m", replies: 1 },
  { id: 2, initials: "KS", name: "Karan Singh", time: "00:32", body: "Love this frame. Could the product logo enter just a touch earlier?", age: "12m", replies: 0 },
  { id: 3, initials: "RK", name: "Rhea Kapoor", time: "00:47", body: "This supersedes my note on V1 — the grade is working beautifully now.", age: "5m", replies: 0 },
];

export function MediaReview({ token }: { token: string }) {
  const [playing, setPlaying] = useState(false);
  const [activeComment, setActiveComment] = useState<number | null>(1);
  const [mobileComments, setMobileComments] = useState(false);
  const reduced = useReducedMotion();
  return <main className="min-h-screen bg-[#090b13] text-white">
    <header className="flex h-16 items-center gap-4 border-b border-white/[.08] px-4 md:px-6"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-xl bg-gradient-to-br from-violet-500 to-cyan-400 text-xs font-black">A</span><span className="display text-sm font-bold">AndThenn</span></div><span className="h-4 w-px bg-white/10"/><div className="min-w-0"><p className="truncate text-xs font-semibold text-zinc-200">Aster House · Monsoon Stories</p><p className="truncate text-[10px] text-zinc-600">Hero Film — V2 · shared 04 Aug</p></div><div className="ml-auto flex items-center gap-1"><button aria-label="Copy share link" className="grid size-10 place-items-center rounded-xl text-zinc-400 hover:bg-white/10 hover:text-white"><Link2 size={17}/></button><button aria-label="Download version" className="hidden size-10 place-items-center rounded-xl text-zinc-400 hover:bg-white/10 hover:text-white sm:grid"><Download size={17}/></button><button aria-label="More" className="grid size-10 place-items-center rounded-xl text-zinc-400 hover:bg-white/10 hover:text-white"><MoreHorizontal size={18}/></button></div></header>
    <div className="grid min-h-[calc(100vh-4rem)] lg:grid-cols-[1fr_370px]">
      <section className="relative flex min-w-0 flex-col"><div className="relative flex min-h-[60vh] flex-1 items-center justify-center overflow-hidden p-4 md:p-8">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(109,68,229,.13),transparent_35%)]"/>
        <div className="relative aspect-video w-full max-w-5xl overflow-hidden rounded-lg bg-[#1a2030] shadow-2xl shadow-black/60 ring-1 ring-white/10">
          <div className="absolute inset-0 bg-[linear-gradient(135deg,#1e293b_0%,#203a43_38%,#2c5364_64%,#111827_100%)]"><div className="absolute inset-0 opacity-50 [background:radial-gradient(circle_at_25%_30%,#22d3ee55,transparent_20%),radial-gradient(circle_at_70%_55%,#a78bfa66,transparent_26%)]"/><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-black/60 to-transparent"/><div className="absolute bottom-[18%] left-[8%]"><p className="display text-[clamp(1.4rem,4vw,3.8rem)] font-bold tracking-tight">When the rain arrives,</p><p className="display text-[clamp(1.4rem,4vw,3.8rem)] font-light text-cyan-200">the city remembers.</p></div></div>
          {[{left:"27%",top:"34%",id:1},{left:"54%",top:"58%",id:2},{left:"76%",top:"42%",id:3}].map((marker)=><button key={marker.id} onClick={()=>setActiveComment(marker.id)} aria-label={`Open comment ${marker.id}`} style={{left:marker.left,top:marker.top}} className={cn("absolute grid size-7 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full text-[10px] font-black shadow-lg ring-2 ring-white/70 transition-transform hover:scale-110",activeComment===marker.id?"bg-violet-500":"bg-zinc-950/85")}>{marker.id}</button>)}
          {!playing && <button onClick={()=>setPlaying(true)} aria-label="Play video" className="absolute left-1/2 top-1/2 grid size-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-zinc-950 shadow-2xl transition-transform hover:scale-105"><Play size={25} fill="currentColor" className="ml-1"/></button>}
        </div>
      </div>
      <div className="border-t border-white/[.08] bg-[#0d0f18] px-4 py-4 md:px-6"><div className="mx-auto max-w-5xl"><div className="relative h-10"><div className="absolute inset-x-0 top-4 h-1 rounded-full bg-white/10"><div className="h-full w-[38%] rounded-full bg-gradient-to-r from-violet-500 to-cyan-400"/></div>{comments.map((comment,index)=><button key={comment.id} onClick={()=>setActiveComment(comment.id)} aria-label={`Comment at ${comment.time}`} className="absolute top-1 size-3 rounded-full bg-fuchsia-400 ring-2 ring-[#0d0f18]" style={{left:`${[28,57,81][index]}%`}} />)}<span className="absolute top-0 h-9 w-px bg-white" style={{left:"38%"}}/></div><div className="flex items-center gap-4"><button onClick={()=>setPlaying(!playing)} aria-label={playing?"Pause":"Play"}>{playing?<Pause size={19} fill="currentColor"/>:<Play size={19} fill="currentColor"/>}</button><Volume2 size={17} className="text-zinc-400"/><span className="text-xs tabular-nums text-zinc-400">00:24 / 01:04</span><button onClick={()=>setMobileComments(true)} className="ml-auto flex min-h-10 items-center gap-2 rounded-xl bg-white/10 px-3 text-xs font-bold lg:hidden"><MessageSquare size={15}/> Comments <span className="rounded-full bg-violet-500 px-1.5">3</span></button><button aria-label="Fullscreen" className="ml-auto hidden text-zinc-400 lg:block"><Expand size={17}/></button></div></div></div>
      </section>
      <CommentRail activeComment={activeComment} setActiveComment={setActiveComment} className="hidden lg:flex" token={token}/>
    </div>
    <AnimatePresence>{mobileComments&&<motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/60 lg:hidden" onClick={()=>setMobileComments(false)}><motion.div initial={reduced?false:{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{type:"spring",damping:28,stiffness:280}} className="absolute inset-x-0 bottom-0 h-[72vh] overflow-hidden rounded-t-3xl bg-[#11131d]" onClick={(e)=>e.stopPropagation()}><button aria-label="Close comments" onClick={()=>setMobileComments(false)} className="absolute right-4 top-3 z-10 grid size-10 place-items-center rounded-xl bg-white/10"><X size={17}/></button><CommentRail activeComment={activeComment} setActiveComment={setActiveComment} token={token}/></motion.div></motion.div>}</AnimatePresence>
  </main>;
}

function CommentRail({activeComment,setActiveComment,className,token}:{activeComment:number|null;setActiveComment:(id:number)=>void;className?:string;token:string}) {
  return <aside className={cn("flex-col border-l border-white/[.08] bg-[#11131d]",className)}><div className="border-b border-white/[.08] p-5"><div className="flex items-center justify-between"><h2 className="display text-lg font-bold">Feedback</h2><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold text-zinc-300">3 comments</span></div><button className="mt-4 flex w-full items-center justify-between rounded-xl border border-white/10 bg-white/[.04] px-3 py-2.5 text-left text-xs"><span><span className="block font-bold">Reviewing as Rhea Kapoor</span><span className="text-[10px] text-zinc-500">rhea@asterhouse.in</span></span><ChevronDown size={14}/></button></div><div className="scrollbar-none flex-1 space-y-2 overflow-y-auto p-3">{comments.map(comment=><button onClick={()=>setActiveComment(comment.id)} key={comment.id} className={cn("w-full rounded-2xl border p-4 text-left transition-colors",activeComment===comment.id?"border-violet-500/60 bg-violet-500/10":"border-transparent hover:bg-white/[.04]")}><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-cyan-500 text-[9px] font-black">{comment.initials}</span><span className="flex-1"><span className="block text-xs font-bold">{comment.name}</span><span className="text-[10px] text-zinc-600">{comment.age} ago</span></span><span className="rounded-md bg-violet-400/15 px-2 py-1 text-[10px] font-bold text-violet-300">{comment.time}</span></div><p className="mt-3 text-xs leading-5 text-zinc-300">{comment.body}</p>{comment.replies>0&&<span className="mt-3 block text-[10px] font-bold text-cyan-300">1 reply · View thread</span>}</button>)}</div><form className="border-t border-white/[.08] p-4" onSubmit={(e)=>e.preventDefault()}><label className="sr-only" htmlFor={`comment-${token}`}>Add a comment</label><div className="rounded-2xl border border-white/10 bg-white/[.04] p-3 focus-within:border-violet-500/60"><textarea id={`comment-${token}`} rows={2} placeholder="Add feedback at 00:24…" className="w-full resize-none bg-transparent text-xs leading-5 text-white outline-none placeholder:text-zinc-600"/><div className="mt-2 flex items-center justify-between"><button type="button" className="flex items-center gap-1 text-[10px] font-bold text-zinc-500"><Check size={12}/> Draw on frame</button><Button size="sm" aria-label="Send comment"><Send size={13}/></Button></div></div><p className="mt-2 text-center text-[9px] text-zinc-700">Shared securely by AndThenn · pinned to V2</p></form></aside>;
}
