"use client";
import { Badge, Button, cn } from "@andthenn/ui";
import { motion } from "motion/react";
import { CalendarDays, ChevronDown, CircleDot, Clock3, ListFilter, MessageSquare, MoreHorizontal, Paperclip, Plus, Rows3, Search } from "lucide-react";
import { useState } from "react";
import { stages } from "../lib/demo-data";

export function ProjectBoard() {
  const [view, setView] = useState<"board" | "list">("board");
  return <>
    <div className="surface mb-4 flex flex-wrap items-center gap-2 rounded-2xl p-2"><div className="flex rounded-xl bg-zinc-100 p-1"><button onClick={() => setView("board")} className={cn("flex min-h-9 items-center gap-2 rounded-lg px-3 text-xs font-bold", view === "board" && "bg-white shadow-sm")}><Rows3 size={14} /> Board</button><button onClick={() => setView("list")} className={cn("flex min-h-9 items-center gap-2 rounded-lg px-3 text-xs font-bold", view === "list" && "bg-white shadow-sm")}><ListFilter size={14} /> List</button></div><button className="ml-1 flex min-h-9 items-center gap-2 rounded-lg px-3 text-xs font-semibold text-zinc-500 hover:bg-zinc-100"><CalendarDays size={14} /> Due date <ChevronDown size={13} /></button><button className="flex min-h-9 items-center gap-2 rounded-lg px-3 text-xs font-semibold text-zinc-500 hover:bg-zinc-100"><CircleDot size={14} /> Assignee <ChevronDown size={13} /></button><button className="ml-auto grid size-9 place-items-center rounded-lg text-zinc-500 hover:bg-zinc-100" aria-label="Search tasks"><Search size={16} /></button><Button size="sm"><Plus size={14} /> Add task</Button></div>
    {view === "board" ? <div className="grid items-start gap-3 overflow-x-auto pb-3 md:grid-cols-2 xl:grid-cols-4">{stages.map((stage) => <section key={stage.id} className="min-w-[260px] rounded-2xl bg-zinc-100/70 p-2"><header className="flex items-center gap-2 px-2 py-2"><span className="size-2 rounded-full" style={{ backgroundColor: stage.color }} /><h3 className="text-xs font-bold">{stage.label}</h3><span className="text-[10px] font-bold text-zinc-400">{stage.tasks.length}</span><button className="ml-auto text-zinc-400"><MoreHorizontal size={15} /></button></header><div className="space-y-2">{stage.tasks.map((task) => <motion.article layout key={task.title} whileHover={{ y: -2 }} className="cursor-pointer rounded-xl border border-zinc-200 bg-white p-3.5 shadow-sm"><div className="flex items-start justify-between gap-2"><Badge tone={task.tag === "Video" ? "violet" : task.tag === "Audio" ? "cyan" : "neutral"}>{task.tag}</Badge><MoreHorizontal size={14} className="text-zinc-300" /></div><h4 className="mt-3 text-sm font-bold leading-5">{task.title}</h4><div className="mt-4 flex items-center text-[10px] text-zinc-400"><span className="grid size-6 place-items-center rounded-full bg-zinc-900 font-bold text-white">{task.owner}</span><span className="ml-2 flex items-center gap-1"><Clock3 size={11} /> {task.due}</span><span className="ml-auto flex gap-2"><Paperclip size={12} /><MessageSquare size={12} /></span></div></motion.article>)}</div><button className="mt-2 flex min-h-9 w-full items-center justify-center gap-1 rounded-xl text-xs font-bold text-zinc-400 hover:bg-white hover:text-violet-600"><Plus size={13} /> Add task</button></section>)}</div> : <div className="surface overflow-hidden rounded-2xl"><div className="grid grid-cols-[1fr_120px_110px_100px] border-b border-zinc-100 px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-zinc-400"><span>Task</span><span>Stage</span><span>Owner</span><span>Due</span></div>{stages.flatMap((stage) => stage.tasks.map((task) => <div key={task.title} className="grid grid-cols-[1fr_120px_110px_100px] items-center border-b border-zinc-100 px-5 py-4 text-xs"><span className="font-bold">{task.title}</span><span>{stage.label}</span><span>{task.owner}</span><span>{task.due}</span></div>))}</div>}
  </>;
}
