"use client";
import { PreservingForm } from "./preserving-form";
import { useActionState } from "react";
import { runProjectCommand } from "../app/(erp)/project-command";

function Command({ projectId, command, label, fields = {} }: { projectId: string; command: string; label: string; fields?: Record<string, string> }) {
  const [state, action, pending] = useActionState(runProjectCommand, {});
  return <PreservingForm action={action} className="py-2"><input type="hidden" name="projectId" value={projectId}/><input type="hidden" name="command" value={command}/>{Object.entries(fields).map(([name, value]) => <input key={name} type="hidden" name={name} value={value}/>)}<button disabled={pending} className="min-h-11 rounded-xl border border-violet-200 bg-violet-50 px-4 text-sm font-bold text-violet-800 disabled:opacity-50">{pending ? "Saving…" : label}</button>{state.error && <p role="alert" className="mt-2 text-sm text-rose-700">{state.error}</p>}{state.success && <p role="status" className="mt-2 text-sm text-emerald-700">{state.success}</p>}</PreservingForm>;
}

export function ProjectCloseout({ projectId, status, outputs, checklist, archiveStatus }: { projectId: string; status: string; outputs: { id: string; name: string; status: string }[]; checklist: { id: string; label: string; completed: boolean }[]; archiveStatus: string | null }) {
  return <section aria-label="Delivery and closure" className="surface mb-4 rounded-2xl p-5"><h2 className="display text-lg font-bold">Delivery and closure</h2><p className="mt-1 text-sm text-zinc-600">Confirm completed outputs, verify the checklist, then archive before closing. File approval alone never completes work.</p>{outputs.filter((output) => output.status === "READY_FOR_MANAGER_CONFIRMATION").map((output) => <Command key={output.id} projectId={projectId} command="confirm-output" fields={{ deliverableId: output.id }} label={`Confirm output: ${output.name}`}/>)}{status === "READY_FOR_FINAL_CLOSURE" ? <div className="mt-3">{!checklist.length && <Command projectId={projectId} command="prepare" label="Prepare closure checklist"/>}{checklist.map((item) => <Command key={item.id} projectId={projectId} command="check" fields={{ itemId: item.id }} label={`${item.completed ? "Undo" : "Verify"}: ${item.label}`}/>)}<p className="my-3 text-sm font-semibold">Archive: {archiveStatus ?? "Not started"}</p>{(!archiveStatus || archiveStatus === "FAILED") && <Command projectId={projectId} command="archive" label="Create verified archive"/>}{archiveStatus === "SUCCEEDED" && checklist.length > 0 && checklist.every((item) => item.completed) && <Command projectId={projectId} command="close" label="Close project"/>}<p className="mt-2 text-xs text-zinc-500">Refresh after archive processing to see its verified result.</p></div> : <p className="mt-3 text-sm font-semibold">{status === "COMPLETED" ? "Project completed and archived." : "All tasks must be confirmed, then all outputs confirmed, before final closure."}</p>}</section>;
}
