import { ExpenseCorrection } from "../../../components/expense-correction";
import { getFinanceSummary } from "../../../lib/finance-summary";
import { Badge, Button } from "@andthenn/ui";
import { can } from "@andthenn/domain";
import { CircleDollarSign, Landmark, Plus, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { PageHeading } from "../../../components/page-heading";
import { resolveActorContext } from "../../../lib/actor-context";
import { createProjectExpense } from "../actions";

const money = (minor: number, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(minor / 100);

export default async function AccountsPage() {
  const actor = await resolveActorContext(); if (!actor) return null; if (!can(actor, "finances:view")) notFound();
  const { rows, totals, expenseRows, projectRows } = await getFinanceSummary(actor);
  return <><PageHeading eyebrow="Founder finance · operational, not a ledger" title="Accounts" action={<a href="/api/reports/finance-export" className="inline-flex min-h-11 items-center text-sm font-bold text-violet-700">Export finance CSV</a>} description="Budgets, latest quotes, invoices, paid revenue, project expenses, and gross profit reconcile by project. Totals are grouped by currency. Partial invoices are shown separately from paid revenue."/>
    {totals.map((total) => <section data-walkthrough="accounts" key={total.currency} aria-label={`${total.currency} finance summary`} className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Landmark} label={`${total.currency} Budget`} value={money(total.budget, total.currency)}/><Metric icon={ReceiptText} label="Invoiced" value={money(total.invoiced, total.currency)}/><Metric icon={CircleDollarSign} label="Paid revenue" value={money(total.revenue, total.currency)}/><Metric icon={CircleDollarSign} label="Operational gross profit" value={money(total.revenue-total.expense, total.currency)}/><Metric icon={ReceiptText} label="Partial invoices (invoice totals)" value={money(total.partial, total.currency)}/><Metric icon={ReceiptText} label="Recorded expenses" value={money(total.expense, total.currency)}/></section>)}

    <details className="surface mb-4 rounded-2xl p-5"><summary className="cursor-pointer text-sm font-bold text-violet-700">Record project expense</summary><form action={createProjectExpense} className="mt-4 grid gap-3 md:grid-cols-5"><label className="text-xs font-bold text-zinc-600">Project<select name="projectId" required className="control mt-1.5">{projectRows.map((project) => <option key={project.id} value={project.id}>{project.name} · {project.currency}</option>)}</select></label><label className="text-xs font-bold text-zinc-600">Category<select name="category" required className="control mt-1.5"><option>Production</option><option>Freelancer</option><option>Travel</option><option>Equipment</option><option>Post-production</option><option>Other</option></select></label><label className="text-xs font-bold text-zinc-600">Amount<input name="amountMajor" inputMode="decimal" required pattern="\d+(\.\d{1,2})?" placeholder="12500.00" className="control mt-1.5"/></label><label className="text-xs font-bold text-zinc-600">Incurred on<input name="incurredOn" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} className="control mt-1.5"/></label><label className="text-xs font-bold text-zinc-600">Note<input name="note" maxLength={1000} className="control mt-1.5" placeholder="Optional reference"/></label><Button type="submit" className="min-h-11 md:col-span-5 md:justify-self-end"><Plus size={15}/> Add expense</Button></form></details>
    <section aria-label="Expense corrections" className="surface mb-4 overflow-hidden rounded-2xl"><h2 className="p-5 text-lg font-bold">Expense history and corrections</h2>{expenseRows.map((expense) => <ExpenseCorrection key={expense.id} expense={expense} project={projectRows.find((project) => project.id === expense.projectId)?.name ?? "Project"}/>)}{!expenseRows.length && <p className="px-5 pb-5 text-sm text-zinc-500">No expense entries yet.</p>}</section>
    <section className="surface overflow-hidden rounded-2xl"><div className="hidden grid-cols-[minmax(210px,1.5fr)_repeat(5,minmax(105px,1fr))] border-b border-zinc-100 px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-zinc-500 lg:grid"><span>Project</span><span>Budget</span><span>Latest quote</span><span>Invoice</span><span>Expenses</span><span>Margin / GP</span></div><div className="divide-y divide-zinc-100">{rows.map((row) => <article key={`${row.id}:${row.currency}`} className="grid gap-3 p-5 lg:grid-cols-[minmax(210px,1.5fr)_repeat(5,minmax(105px,1fr))] lg:items-center"><div><strong className="block text-sm">{row.name}</strong><span className="mt-1 flex flex-wrap gap-1"><Badge tone={row.status === "COMPLETED" ? "green" : "violet"}>{row.status.replaceAll("_", " ")}</Badge><Badge tone="neutral">{row.currency}</Badge></span></div><FinanceCell label="Budget" value={money(row.budget, row.currency)}/><div><FinanceCell label={`Latest estimate · ${row.quoteStatus}`} value={money(row.quoted, row.currency)}/><FinanceCell label="Accepted quote" value={row.acceptedQuote === null ? "—" : money(row.acceptedQuote, row.currency)}/></div><FinanceCell label={row.invoiceStatus.replaceAll("_", " ")} value={money(row.invoiced, row.currency)}/><FinanceCell label={`${row.expenses.length} entries`} value={money(row.expense, row.currency)}/><div><FinanceCell label="Operational gross profit" value={money(row.grossProfit, row.currency)} danger={row.grossProfit < 0}/><FinanceCell label="Estimated margin" value={money(row.estimatedMargin, row.currency)} danger={row.estimatedMargin < 0}/></div></article>)}</div>{!rows.length && <p className="p-10 text-center text-sm text-zinc-500">No projects are available for financial reporting.</p>}</section></>;
}

function Metric({ icon: Icon, label, value, tone }: { icon: typeof Landmark; label: string; value: string; tone?: "rose" | "green" }) { return <div className="surface rounded-2xl p-4"><Icon size={17} className={tone === "rose" ? "text-rose-600" : tone === "green" ? "text-emerald-600" : "text-violet-600"}/><p className="mt-3 text-xs font-semibold text-zinc-500">{label}</p><p className="display mt-1 text-2xl font-bold">{value}</p></div>; }
function FinanceCell({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div><span className="text-[10px] font-bold uppercase tracking-wide text-zinc-400 lg:hidden">{label}</span><strong className={`block text-sm ${danger ? "text-rose-700" : "text-zinc-800"}`}>{value}</strong><small className="text-[10px] text-zinc-500">{label}</small></div>; }
