import { expect, test } from "@playwright/test";

test("CRM-R1 detail edits preserve the assigner and pending completion authority", async ({ page, context }) => {
  await page.goto("/login"); await page.getByRole("button", { name: /^Manager/ }).click(); await expect(page).toHaveURL(/\/home$/);
  await page.goto("/work?new=task");
  const name = `Accountability ${Date.now()}`;
  await page.getByLabel("Task name").fill(name);
  await page.getByLabel("Primary owner").selectOption({ label: "Arjun Menon · designer" });
  const dueInput = page.getByLabel("Due date");
  await expect(dueInput).toBeEnabled();
  const originalDue = await dueInput.inputValue();
  await expect(dueInput).toHaveAttribute("max", originalDue);
  expect(await dueInput.evaluate((input: HTMLInputElement) => input.validity.valid)).toBe(true);
  await page.getByRole("button", { name: "Create task", exact: true }).click();
  await expect(page).toHaveURL(/\/tasks\//);
  const taskUrl = page.url(), taskId = taskUrl.split("/").pop()!;
  const projectUrl = await page.locator('a[href^="/projects/"]').first().getAttribute("href");
  await page.goto("/login"); await context.clearCookies(); await page.getByRole("button", { name: /^Designer/ }).click(); await expect(page).toHaveURL(/\/home$/);
  await page.goto(taskUrl); await page.getByRole("button", { name: "Request completion", exact: true }).click();
  await expect(page.getByRole("button", { name: "Update and withdraw request", exact: true })).toBeVisible();
  await page.goto(`/projects?project=${projectUrl!.split("/").pop()}&task=${taskId}`);
  await expect(page.getByLabel("Due date")).toHaveValue(originalDue);
  const revisedName = `${name} revised`;
  await page.getByLabel("Task name").fill(revisedName);
  await page.getByLabel("Brief", { exact: true }).fill("Clarified the brief without changing ownership.");
  await page.getByRole("button", { name: "Save task", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(page).toHaveURL(/\/projects\?project=[^&]+$/);
  await expect(page.getByRole("button", { name: revisedName, exact: true })).toBeVisible();
  await page.goto(taskUrl);
  await expect(page.getByText(/Assigned by Rohan Bose/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Request completion", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Confirm completion", exact: true })).toHaveCount(0);
  await page.goto("/login"); await context.clearCookies(); await page.getByRole("button", { name: /^Manager/ }).click(); await expect(page).toHaveURL(/\/home$/);
  await page.goto(taskUrl); await page.getByRole("button", { name: "Confirm completion", exact: true }).click();
  await expect(page.getByRole("button", { name: "Confirm completion", exact: true })).toHaveCount(0);
});
