import { expect, test, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";
test.use({ actionTimeout: 15000 });

async function login(page: Page, persona: string) {
  await page.context().clearCookies(); await page.goto("/login");
  await page.getByRole("button", { name: new RegExp(`^${persona}`) }).click();
  await expect(page).toHaveURL(/\/home$/);
}
for (const approvalMode of ["portal", "external"] as const) test(`golden brief, version revisions, ${approvalMode} Client decision, delivery and verified closure`, async ({ page, browser }, info) => {
  test.setTimeout(180_000);
  const title = `Golden delivery ${Date.now()}`;
  await login(page, "Manager"); await page.goto("/intake");
  await page.locator("#intake-title").fill(title); await page.locator("#intake-summary").fill("Create a final film, review revisions, deliver and archive.");
  await page.getByRole("button", { name: "Manual intake", exact: true }).click();
  await page.getByRole("link").filter({ hasText: title }).click();
  await page.getByRole("button", { name: "Approve & set up" }).click();
  await page.getByRole("combobox", { name: "Client", exact: true }).selectOption({ label: "Aster House" });
  await page.getByRole("button", { name: "Save & continue" }).click();
  await page.getByLabel("Task name", { exact: true }).fill(`${title} film`);
  await page.getByLabel("Primary owner", { exact: true }).selectOption({ label: "Arjun Menon" });
  await page.getByRole("button", { name: "Save & continue" }).click();
  await page.getByRole("button", { name: "Confirm & create project" }).click();
  await expect(page).toHaveURL(/\/projects\?project=/);
  const projectId = new URL(page.url()).searchParams.get("project")!;
  const projectUrl = `/projects/${projectId}`;
  await page.goto(projectUrl);
  await page.getByRole("button", { name: "Update Client access" }).click();
  await expect(page.getByText("Client access granted.", { exact: true })).toBeVisible();
  await page.getByRole("link").filter({ hasText: `${title} film` }).click();
  await expect(page).toHaveURL(/\/tasks\//);
  const taskUrl = page.url();
  await login(page, "Designer"); await page.goto(taskUrl);
  await page.getByRole("button", { name: "Request completion", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "Publish the Client-approved final version" })).toContainText("Publish the Client-approved final version");
  const fixture = Buffer.from((await readFile("packages/db/fixtures/prototype-review.mp4.base64", "utf8")).trim(), "base64");
  async function upload(version: number) {
    await login(page, "Designer"); await page.goto(taskUrl);
    const form = page.locator("form").filter({ has: page.getByRole("heading", { name: "Upload a version" }) });
    await form.locator('[name="logicalName"]').fill(`${title} master`);
    if (version > 1) await form.locator('[name="fileAssetId"]').selectOption({ label: `New version of ${title} master` });
    await form.locator('input[type="file"]').setInputFiles({ name: `golden-v${version}.mp4`, mimeType: "video/mp4", buffer: fixture });
    await form.getByRole("button", { name: "Upload", exact: true }).click();
    await expect(page.getByText("Upload complete.", { exact: false })).toBeVisible();
    await expect(async () => { await page.reload(); await expect(page.locator("form").filter({ has: page.getByRole("heading", { name: "Internal review candidate" }) }).locator("option").filter({ hasText: `V${version} · golden-v${version}.mp4` })).toHaveCount(1); }).toPass({ timeout: 30000 });
    const candidate = page.locator("form").filter({ has: page.getByRole("heading", { name: "Internal review candidate" }) });
    await candidate.locator("select").selectOption({ label: `V${version} · golden-v${version}.mp4` });
    await candidate.getByRole("button", { name: "Select version" }).click();
    await expect(page.getByText("Internal review version selected.", { exact: true })).toBeVisible();
  }
  await upload(1);
  await page.locator('select[name="targetStageId"]').selectOption({ label: "Internal review" });
  await page.getByRole("button", { name: "Move task", exact: true }).click();
  await expect(page.getByText("Task phase updated.", { exact: true })).toBeVisible();
  await page.reload();
  await login(page, "Manager"); await page.goto(taskUrl);
  await page.getByLabel("Comment", { exact: true }).fill("Internal review: please refine the opening transition.");
  await page.getByRole("button", { name: "Post comment" }).click();
  await expect(page.getByText("Comment posted.")).toBeVisible();
  await page.locator('select[name="targetStageId"]').selectOption({ label: "Changes" });
  await page.getByPlaceholder("Override reason (if needed)").fill("Internal reviewer requested a revised opening.");
  await page.getByRole("button", { name: "Move task", exact: true }).click();
  await expect(page.getByText("Task phase updated.", { exact: true })).toBeVisible();
  await upload(2);
  async function share(version: number) {
    await login(page, "Manager"); await page.goto(taskUrl);
    const versionId = await page.locator('form').filter({ has: page.getByRole("heading", { name: "Internal review candidate" }) }).locator("select").inputValue();
    await page.getByRole("button", { name: "Clear for Client review", exact: true }).click();
    await expect(page.getByText("Cleared for Client review. Client approval and delivery are still required.", { exact: true })).toBeVisible();
    const clientContext = await browser.newContext();
    const clientPage = await clientContext.newPage();
    await login(clientPage, "Client · Riya");
    expect((await clientPage.request.get(`/api/files/${versionId}`)).status()).toBe(404);
    await clientContext.close();
    const form = page.locator("form").filter({ has: page.getByRole("heading", { name: "Create pinned review share" }) });
    await form.locator('[name="fileVersionId"]').selectOption({ label: `V${version} · golden-v${version}.mp4` });
    await form.getByRole("button", { name: "Share version" }).click();
    await expect(page.getByRole("button", { name: "Copy review link" })).toBeVisible();
  }
  await share(2);
  await login(page, "Client · Riya"); await page.goto(projectUrl);
  let decision = page.getByRole("region", { name: "Client decisions" });
  await decision.getByLabel("Feedback", { exact: true }).fill("Please revise the ending before final approval.");
  await decision.getByRole("button", { name: "Send decision" }).click();
  await expect(decision.getByRole("status")).toContainText("Changes sent");
  await upload(3); await share(3);
  await login(page, "Client · Riya"); await page.goto(projectUrl);
  decision = page.getByRole("region", { name: "Client decisions" });
  if (approvalMode === "portal") {
    await decision.getByLabel("Your decision").selectOption("APPROVE");
    await decision.getByRole("button", { name: "Send decision" }).click();
    await expect(decision.getByRole("status")).toContainText("Version approved");
  } else {
    await login(page, "Manager"); await page.goto(taskUrl);
    const external = page.locator("details").filter({ has: page.locator("summary", { hasText: "Record Client approval received externally" }) });
    await external.locator("summary").click();
    await external.getByLabel("Client approver", { exact: true }).fill("Riya Malhotra");
    await external.getByLabel("Approval received at").fill("2026-09-01T10:00");
    await external.getByLabel("Evidence reference").fill("acceptance-message-123");
    await external.getByLabel("Approval note").fill("Client explicitly approved version three by email.");
    await external.getByRole("button", { name: "Record Client approval", exact: true }).click();
    await expect(external.getByRole("status")).toContainText("Client approval recorded");
  }
  await login(page, "Manager"); await page.goto(taskUrl);
  const approvedVersionId = await page.locator("form").filter({ has: page.getByRole("heading", { name: "Internal review candidate" }) }).locator("select").inputValue();
  const beforeDelivery = await browser.newContext(); const beforeDeliveryPage = await beforeDelivery.newPage();
  await login(beforeDeliveryPage, "Client · Riya");
  expect((await beforeDeliveryPage.request.get(`/api/files/${approvedVersionId}`)).status()).toBe(404);
  await beforeDelivery.close();
  await page.getByRole("button", { name: "Publish final delivery", exact: true }).click();
  await expect(page.getByText("Final delivery published.", { exact: true })).toBeVisible();
  await login(page, "Client · Riya"); await page.goto(projectUrl);
  const final = page.locator('a[href^="/api/files/"]').filter({ hasText: `${title} master` });
  expect((await page.request.get((await final.getAttribute("href"))!)).status()).toBe(200);
  const clientContext = await browser.newContext(); const clientPage = await clientContext.newPage();
  await login(clientPage, "Client · Riya"); await clientPage.goto(projectUrl);
  await login(page, "Manager"); await page.goto(projectUrl); await page.getByRole("combobox", { name: "Access action" }).selectOption("revoke"); await page.getByRole("button", { name: "Update Client access" }).click();
  await expect(page.getByRole("status")).toContainText("revoked");
  await clientPage.reload(); await expect(clientPage.getByRole("heading", { name: "404" })).toBeVisible(); await clientContext.close();
  await login(page, "Designer"); await page.goto(taskUrl);
  await page.locator('select[name="targetStageId"]').selectOption({ label: "Final delivery" });
  await page.getByRole("button", { name: "Move task", exact: true }).click();
  await expect(page.getByText("Task phase updated.", { exact: true })).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "Request completion", exact: true }).click();
  await expect(page.getByRole("button", { name: "Update and withdraw request" })).toBeVisible();
  await login(page, "Manager"); await page.goto(taskUrl); await page.getByRole("button", { name: "Confirm completion", exact: true }).click();
  await expect(page.getByText("COMPLETED", { exact: true })).toBeVisible();
  await page.goto(projectUrl); await page.getByRole("button", { name: /^Confirm output:/ }).click();
  await page.getByRole("button", { name: "Prepare closure checklist" }).click();
  for (const label of ["Final approved files verified", "Rights and releases checked", "Invoice status reviewed", "Archive destination confirmed"]) await page.getByRole("button", { name: `Verify: ${label}`, exact: true }).click();
  await page.getByRole("button", { name: "Create verified archive" }).click();
  await expect(async () => { await page.reload(); await expect(page.getByRole("button", { name: "Close project", exact: true })).toBeVisible(); }).toPass({ timeout: 30000 });
  await page.getByRole("button", { name: "Close project", exact: true }).click();
  await expect(page.getByText("Project completed and archived.")).toBeVisible();
  await page.reload(); await expect(page.getByText("Project completed and archived.")).toBeVisible();
  await page.screenshot({ path: info.outputPath("golden-completed.png"), fullPage: true });
});
