import { expect, test } from "@playwright/test";
test.use({ actionTimeout: 15000 });
test("relationship edits and stale expense corrections remain permission gated", async ({ page, context }, info) => {
  await page.goto("/login"); await page.getByRole("button", { name: /^Manager/ }).click(); await expect(page).toHaveURL(/\/home$/);
  await page.goto("/clients/23000000-0000-4000-8000-000000000001");
  const relationship = page.locator('details[aria-label="Relationship editing"]');
  await expect(page.getByRole("heading", { name: "Aster House" })).toBeVisible();
  await expect(relationship).toBeVisible();
  await expect(relationship).not.toHaveAttribute("open", "");
  await page.setViewportSize({ width: 375, height: 812 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("client-relationship-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await relationship.locator("summary").first().click();
  const brand = `Acceptance brand ${Date.now()}`;
  const add = relationship.locator("details").filter({ has: page.locator("summary", { hasText: /^Add brand$/ }) });
  await add.locator("summary").first().click(); await add.getByLabel("Name", { exact: true }).fill(brand);
  await add.getByRole("button", { name: "Save brand" }).click(); await expect(add.getByRole("status")).toContainText("saved");
  await page.reload(); await relationship.locator("summary").first().click(); await expect(page.locator("summary", { hasText: `Edit brand: ${brand}` })).toBeVisible();
  await page.goto("about:blank"); await page.context().clearCookies(); await page.goto("/login"); await page.getByRole("button", { name: /^Founder/ }).click(); await expect(page).toHaveURL(/\/home$/);
  await page.goto("/accounts");
  const record = page.locator("details").filter({ has: page.locator("summary", { hasText: /^Record project expense$/ }) });
  await record.locator("summary").click(); await record.getByLabel("Amount", { exact: true }).fill("12.34");
  await record.getByRole("button", { name: "Add expense" }).click();
  const correction = page.locator("details").filter({ has: page.locator("summary", { hasText: /12\.34 · Correct entry/ }) });
  await expect(correction).toHaveCount(1);
  const other = await context.newPage(); await other.goto("/accounts");
  const stale = other.locator("details").filter({ has: other.locator("summary", { hasText: /12\.34 · Correct entry/ }) });
  await stale.locator("summary").click(); await stale.getByLabel("Correction reason").fill("Stale edit must be rejected."); await stale.getByLabel(/Amount/).fill("22.22");
  await correction.locator("summary").click(); await correction.getByLabel(/Amount/).fill("15.67"); await correction.getByLabel("Correction reason").fill("Corrected receipt amount.");
  await correction.getByRole("button", { name: "Save correction" }).click();
  await expect(page.getByRole("status")).toContainText("Expense corrected");
  await stale.getByRole("button", { name: "Save correction" }).click();
  await expect(stale.getByRole("alert")).toContainText("changed elsewhere"); await expect(stale.getByLabel(/Amount/)).toHaveValue("22.22"); await other.close();
  await page.reload(); await expect(page.locator("summary", { hasText: /15\.67 · Correct entry/ }).first()).toBeVisible();
  await page.setViewportSize({ width: 375, height: 812 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: info.outputPath("expense-mobile.png"), fullPage: true });
  await page.goto("about:blank"); await page.context().clearCookies(); await page.goto("/login"); await page.getByRole("button", { name: /^Designer/ }).click(); await expect(page).toHaveURL(/\/home$/);
  await page.goto("/accounts"); await expect(page).toHaveURL(/\/home$/);
});
