import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import type { StorageProvider, UploadRequest } from "@andthenn/domain";

type Ticket = { key: string; contentType: string; sizeBytes: number; checksumSha256: string; expiresAt: number; mode: "PUT" | "GET" };

/** Filesystem-backed storage for the loopback prototype only. Tickets are
 * authenticated and every completed upload is checksum verified. */
export class LocalFilesystemStorage implements StorageProvider {
  constructor(private readonly root = process.env.PROTOTYPE_DATA_DIR ? join(process.env.PROTOTYPE_DATA_DIR, "storage") : ".prototype/storage", private readonly origin = process.env.APP_URL ?? "http://127.0.0.1:3000", private readonly signingSecret = process.env.PROTOTYPE_SIGNING_SECRET ?? "andthenn-local-prototype-secret") {}
  private objectKey(input: UploadRequest) { const name = input.filename.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g, "-").slice(-120) || "upload.bin"; return `org/${input.organizationId}/tasks/${input.taskId}/versions/${input.fileVersionId}/${name}`; }
  private path(key: string) { const resolved = resolve(this.root, key); if (!resolved.startsWith(resolve(this.root) + "/")) throw new Error("Invalid storage key"); return resolved; }
  private sign(payload: string) { return createHmac("sha256", this.signingSecret).update(payload).digest("base64url"); }
  ticket(value: Ticket) { const payload = Buffer.from(JSON.stringify(value)).toString("base64url"); return `${payload}.${this.sign(payload)}`; }
  verifyTicket(ticket: string): Ticket | null { const [payload, signature] = ticket.split("."); if (!payload || !signature) return null; const expected = this.sign(payload); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; try { const value = JSON.parse(Buffer.from(payload, "base64url").toString()) as Ticket; return value.expiresAt > Date.now() && (value.mode === "GET" || value.mode === "PUT") && !!value.key ? value : null; } catch { return null; } }
  async initiateUpload(input: UploadRequest) { if (input.sizeBytes > 10 * 1024 * 1024) throw new Error("Prototype uploads are limited to 10 MB"); const key = this.objectKey(input), expiresAt = new Date(Date.now() + 15 * 60_000); const ticket = this.ticket({ key, contentType: input.contentType, sizeBytes: input.sizeBytes, checksumSha256: input.checksumSha256, expiresAt: expiresAt.getTime(), mode: "PUT" }); return { uploadId: Buffer.from(key).toString("base64url"), mode: "SINGLE" as const, uploadUrl: `${this.origin}/api/prototype/storage/${ticket}`, expiresAt }; }
  async finalizeUpload(input: UploadRequest & { uploadId: string; parts?: readonly { partNumber: number; etag: string }[] }) { const key = this.objectKey(input); if (Buffer.from(input.uploadId, "base64url").toString() !== key) throw new Error("Upload identity does not match the file version"); const bytes = await readFile(this.path(key)); const checksum = createHash("sha256").update(bytes).digest("hex"); if (bytes.byteLength !== input.sizeBytes || checksum !== input.checksumSha256) throw new Error("Uploaded bytes do not match the declared checksum"); return { objectKey: key, etag: checksum }; }
  async createSignedRead(objectKey: string, expiresInSeconds: number) { const ticket = this.ticket({ key: objectKey, contentType: "application/octet-stream", sizeBytes: 0, checksumSha256: "", expiresAt: Date.now() + expiresInSeconds * 1_000, mode: "GET" }); return `${this.origin}/api/prototype/storage/${ticket}`; }
  async putTicket(ticket: string, bytes: Uint8Array) { const value = this.verifyTicket(ticket); if (!value || value.mode !== "PUT") throw new Error("Invalid or expired upload ticket"); if (bytes.byteLength !== value.sizeBytes || createHash("sha256").update(bytes).digest("hex") !== value.checksumSha256) throw new Error("Upload checksum or size does not match"); const destination = this.path(value.key); await mkdir(dirname(destination), { recursive: true }); const temporary = `${destination}.partial`; await writeFile(temporary, bytes); await rename(temporary, destination); return value; }
  async openRead(objectKey: string, range?: string) { const path = this.path(objectKey); const bytes = await readFile(path); let start = 0, end = bytes.length - 1; if (range) { const match = /^bytes=(\d+)-(\d*)$/.exec(range); if (!match) throw new Error("Invalid byte range"); start = Number(match[1]); end = match[2] ? Number(match[2]) : end; if (start > end || end >= bytes.length) throw new Error("Requested range is unavailable"); } const slice = bytes.subarray(start, end + 1); return { body: new ReadableStream({ start(controller) { controller.enqueue(slice); controller.close(); } }), contentLength: slice.byteLength, contentRange: range ? `bytes ${start}-${end}/${bytes.length}` : null, contentType: "application/octet-stream", etag: createHash("sha256").update(bytes).digest("hex") }; }
  async storeEvidence(input: { organizationId: string; intakeItemId: string; sourceItemId: string; filename: string; contentType: string; bytes: Uint8Array }) { const key = `org/${input.organizationId}/intake/${input.intakeItemId}/sources/${input.sourceItemId}/${input.filename.replace(/[^a-zA-Z0-9._-]+/g, "-")}`; const path = this.path(key); await mkdir(dirname(path), { recursive: true }); await writeFile(path, input.bytes); return { storageKey: key, checksumSha256: createHash("sha256").update(input.bytes).digest("hex"), sizeBytes: input.bytes.byteLength }; }
  async copyToArchive(sourceKey: string, destinationKey: string) { const source = await readFile(this.path(sourceKey)); const destination = this.path(destinationKey); await mkdir(dirname(destination), { recursive: true }); await writeFile(destination, source); return { destinationKey }; }
  async quarantine(objectKey: string, restoreUntil: Date) { await this.copyToArchive(objectKey, `quarantine/${restoreUntil.toISOString().slice(0, 10)}/${objectKey}`); }
  async restore(objectKey: string) { if (!objectKey.startsWith("quarantine/")) throw new Error("Invalid quarantine key"); const index = objectKey.indexOf("/org/"); if (index < 0) throw new Error("Invalid quarantine key"); await this.copyToArchive(objectKey, objectKey.slice(index + 1)); }
  async deleteAfterRetention() { /* Retention is deliberately not destructive in the prototype. */ }
  async metadata(objectKey: string) { const bytes = await readFile(this.path(objectKey)); return { sizeBytes: bytes.byteLength, checksumSha256: createHash("sha256").update(bytes).digest("hex"), contentType: "application/octet-stream" }; }
  async healthCheck() { try { await mkdir(this.root, { recursive: true }); return { healthy: true, detail: "Prototype filesystem storage is ready" }; } catch (error) { return { healthy: false, detail: error instanceof Error ? error.message : "Storage unavailable" }; } }
}
