import { isCurrentFinalFile } from "../../../lib/final-file";
import { clients, createDatabase, eq, fileAssets, fileVersions, projects, deliverables, tasks } from "@andthenn/db";
import { Badge } from "@andthenn/ui";
import { FileCheck2 } from "lucide-react";
import Link from "next/link";
import { FileFilters } from "../../../components/file-filters";
import { PageHeading } from "../../../components/page-heading";
import { resolveActorContext } from "../../../lib/actor-context";
import { canReadFile } from "../../../lib/resource-access";

export default async function FilesPage({ searchParams }: { searchParams: Promise<{ q?: string; client?: string; project?: string; type?: string; status?: string }> }) {
  const actor = await resolveActorContext(); if (!actor) return null; const filters = await searchParams; const { db } = createDatabase();
  const allRows = await db.select({ id: fileVersions.id, name: fileAssets.logicalName, filename: fileVersions.filename, contentType: fileVersions.contentType, sizeBytes: fileVersions.sizeBytes, version: fileVersions.versionNumber, status: fileVersions.processingStatus, lockedAt: fileVersions.lockedAt, isCurrentFinal: isCurrentFinalFile, taskId: tasks.id, task: tasks.name, projectId: projects.id, project: projects.name, clientId: clients.id, client: clients.name, createdAt: fileVersions.createdAt }).from(fileVersions).innerJoin(fileAssets, eq(fileAssets.id, fileVersions.fileAssetId)).innerJoin(tasks, eq(tasks.id, fileAssets.taskId)).innerJoin(deliverables, eq(deliverables.id, tasks.deliverableId)).innerJoin(projects, eq(projects.id, deliverables.projectId)).innerJoin(clients, eq(clients.id, projects.clientId)).where(eq(fileVersions.organizationId, actor.organizationId)).orderBy(fileVersions.createdAt);
  const authorized = allRows.filter((file) => canReadFile(actor, { id: file.projectId, clientId: file.clientId, taskId: file.taskId, taskIds: [file.taskId], lockedAt: file.lockedAt, isCurrentFinal: file.isCurrentFinal }));
  const q = filters.q?.trim().toLowerCase() ?? ""; const kind = (contentType: string) => contentType.startsWith("video/") ? "video" : contentType.startsWith("image/") ? "image" : contentType === "application/pdf" ? "pdf" : "other";
  const rows = authorized.filter((file) => (!q || `${file.name} ${file.filename} ${file.task} ${file.project} ${file.client}`.toLowerCase().includes(q)) && (!filters.client || file.clientId === filters.client) && (!filters.project || file.projectId === filters.project) && (!filters.type || kind(file.contentType) === filters.type) && (!filters.status || (filters.status === "FINAL" ? file.isCurrentFinal : file.status === filters.status)));
  const clientsList = [...new Map(authorized.map((file) => [file.clientId, file.client])).entries()]; const projectsList = [...new Map(authorized.filter((file) => !filters.client || file.clientId === filters.client).map((file) => [file.projectId, file.project])).entries()];
  const FileLink = actor.role === "CLIENT" ? "a" : Link;
  return <><PageHeading eyebrow={`${rows.length} of ${authorized.length} versions`} title={actor.role === "CLIENT" ? "Shared files" : "Files"} description={actor.role === "CLIENT" ? "Approved versions in your actively granted projects." : "A permission-scoped library. Version approval and review decisions remain on the owning task."}/>
    <FileFilters key={JSON.stringify(filters)} filters={filters} clients={clientsList} projects={projectsList} statuses={actor.role === "CLIENT" ? [["FINAL", "Approved final"]] : [["READY", "Ready"], ["PROCESSING", "Processing"], ["FAILED", "Failed"], ["FINAL", "Approved final"]]}/>
    <section className="surface overflow-hidden rounded-2xl"><div className="divide-y divide-zinc-100">{rows.map((file) => <FileLink href={actor.role === "CLIENT" ? `/api/files/${file.id}` : `/tasks/${file.taskId}`} key={file.id} className="grid gap-3 p-4 transition hover:bg-violet-50/40 sm:grid-cols-[1fr_160px_130px] sm:items-center"><span className="flex min-w-0 items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-zinc-100 text-zinc-600"><FileCheck2 size={17}/></span><span className="min-w-0"><strong className="block truncate text-sm">{file.name} · v{file.version}</strong><span className="mt-1 block truncate text-xs text-zinc-500">{file.client} · {file.project}{actor.role === "CLIENT" ? "" : ` · ${file.task}`}</span><span className="mt-1 block truncate text-[11px] text-zinc-400">{file.filename} · {(file.sizeBytes / 1_000_000).toFixed(1)} MB</span></span></span><Badge tone={file.isCurrentFinal ? "green" : file.status === "READY" ? "cyan" : file.status === "FAILED" ? "rose" : "amber"}>{file.isCurrentFinal ? "APPROVED FINAL" : file.status}</Badge><span className="text-xs font-semibold text-zinc-500">{file.createdAt.toLocaleDateString()}</span></FileLink>)}</div>{!rows.length && <p className="p-10 text-center text-sm text-zinc-500">No authorized file versions match these filters.</p>}</section></>;
}
